name: myapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rename: ^3.0.2
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  firebase_core: ^3.8.1
  country_code_picker: ^3.1.0
  social_auth_btn_kit: ^0.1.3
  pinput: ^5.0.0
  flutter_osm_plugin: ^1.3.6
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_styles/
    - assets/images/
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
